apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-setup-day
spec:
  selector:
    matchLabels:
      run: pg-setup-day
  replicas: 1
  template:
    metadata:
      labels:
        run: pg-setup-day
    spec:
      containers:
      - name: pg-setup-day
        image: dayerlacher/pg-setup:v2
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 3Gi
            cpu: 2
          requests:
            memory: 100Mi
            cpu: "100m"
---

apiVersion: v1
kind: Service
metadata:
  name: pg-setup-day
  labels:
    run: pg-setup-day
spec:
  ports:
  - port: 8080
  selector:
    run: pg-setup-day