apiVersion: v1
kind: Pod
metadata:
  name: raven
  labels:
    app: raven
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: raven
  restartPolicy: Always